#ifndef PLAYERRESTRICTIONTYPE_HPP
#define PLAYERRESTRICTIONTYPE_HPP

enum class PlayerRestrictionType {
    CANNOT_PLAY_BASIC_CARDS,
    CANNOT_PLAY_INSTANT_CARDS,
    CANNOT_PLAY_UPGRADE_CARDS,
    CANNOT_PLAY_DOWNGRADE_CARDS,
    CANNOT_BE_NEIGHED,
    UNICORN_LIMIT,
    HAND_LIMIT,

};

#endif
